services:
  - type: web
    name: java-rest-api
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: ENVIRONMENT
        value: production

